// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbglnmhhbgimjuwaezzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRiZ2xubWhoYmdpbWp1d2Flenp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3NzYxOTMsImV4cCI6MjA1MzM1MjE5M30.BFcgAMJHgK70yMK_AOYXeMZA9CRz0rSRdKFOc7vn_R4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);